# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/.pub-cache/**"
    - "**/ios/Pods/**"
    - "**/android/.gradle/**"
    - "**/build/**"
    - "**/.dart_tool/**"
  errors:
    # Treat missing required parameters as warnings instead of errors
    missing_required_param: warning
    # Suppress warnings from third-party packages and unused code
    unused_import: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    deprecated_member_use: ignore
    invalid_null_aware_operator: ignore
    # Ignore type coercion warnings
    argument_type_not_assignable: ignore
    # Suppress third-party package specific warnings
    dead_code: ignore
    # Facebook Auth specific
    unused_shown_name: ignore
    # Permission handler specific  
    cast_nullable_to_non_nullable: ignore
    # Google Sign In specific
    null_check_on_nullable_type_parameter: ignore
    # MTB Barcode Scanner specific
    deprecated_colon_for_default_value: ignore

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Disable problematic lints
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    sized_box_for_whitespace: false
    unnecessary_to_list_in_spreads: false
    use_build_context_synchronously: false
    # Keep useful lints enabled  
    avoid_print: false
    prefer_single_quotes: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
