name: project_watch_tower
description: "Project Watch Tower - Watch Together, Discover Together"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.1
  cached_network_image: ^3.3.1
  
  # Networking
  http: ^1.2.2
  dio: ^5.7.0
  
  # Storage
  shared_preferences: ^2.3.2
  
  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  timeago: ^3.7.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Haptics
  haptic_feedback: ^0.5.1+1
  
  # Animations
  lottie: ^3.1.3
  flutter_animate: ^4.5.0
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Authentication (Social login packages commented out for current phase)
  # google_sign_in: ^7.1.1
  # sign_in_with_apple: ^7.0.1
  # local_auth: ^2.3.0
  # Note: Facebook auth completely removed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
  
  # fonts:
  #   - family: SFPro
  #     fonts:
  #       - asset: assets/fonts/SF-Pro-Display-Regular.otf